-- praxis: esquema inicial (PostgreSQL). Derivado das entidades JPA; o Hibernate
-- roda com ddl-auto=validate no perfil prod, entao toda mudanca de entidade
-- exige uma nova migracao V{n}__descricao.sql.
--
-- Enums sao varchar com CHECK (e como o Hibernate mapeia @Enumerated(STRING)
-- no PostgreSQL), nao tipos ENUM nativos: adicionar constante e ALTER de
-- constraint, nao de tipo.

create table processo (
    id                bigint generated by default as identity primary key,
    numero_cnj        varchar(30)  not null unique,
    cliente           varchar(200) not null,
    comarca           varchar(120) not null,
    segredo_justica   boolean      not null,
    responsavel_nome  varchar(120) not null,
    responsavel_email varchar(160) not null,
    responsavel_oab   varchar(20)  not null
);

create table andamento (
    id          bigint generated by default as identity primary key,
    processo_id bigint references processo (id),
    data        date         not null,
    descricao   varchar(500) not null,
    tipo        varchar(20)  not null
        check (tipo in ('INTIMACAO', 'CITACAO', 'AUDIENCIA', 'DESPACHO', 'SENTENCA', 'JUNTADA', 'OUTRO'))
);
create index idx_andamento_processo on andamento (processo_id);

create table prazo (
    id                bigint generated by default as identity primary key,
    numero_processo   varchar(30)  not null,
    descricao         varchar(200) not null,
    intimacao         date         not null,
    quantidade_dias   integer      not null,
    regime            varchar(20)  not null check (regime in ('DIAS_UTEIS', 'DIAS_CORRIDOS')),
    vencimento        date         not null,
    fatal             boolean      not null,
    responsavel_nome  varchar(120) not null,
    responsavel_email varchar(160) not null,
    responsavel_oab   varchar(20)  not null,
    alertas_emitidos  varchar(200),
    cumprido          boolean      not null,
    cumprido_em       date
);
create index idx_prazo_processo on prazo (numero_processo);
create index idx_prazo_vencimento on prazo (vencimento);

create table documento (
    id               bigint generated by default as identity primary key,
    numero_processo  varchar(30) not null,
    tipo             varchar(30) not null
        check (tipo in ('PETICAO_INICIAL', 'CONTESTACAO', 'PROCURACAO', 'PECA_AVULSA')),
    conteudo         text        not null,
    gerado_em        date        not null,
    gerado_por_oab   varchar(20),
    segredo_justica  boolean     not null,
    oabs_habilitadas varchar(500),
    status           varchar(20) not null,
    historico        text
);
create index idx_documento_processo on documento (numero_processo);

create table arquivo_anexo (
    id               bigint generated by default as identity primary key,
    numero_processo  varchar(25)  not null,
    nome             varchar(220) not null,
    tipo             varchar(20)  not null check (tipo in ('PDF', 'JPEG', 'PNG', 'TEXTO')),
    conteudo         bytea        not null,
    descricao        varchar(300),
    anexado_em       date         not null,
    anexado_por_oab  varchar(20),
    segredo_justica  boolean      not null,
    oabs_habilitadas varchar(500)
);
create index idx_anexo_processo on arquivo_anexo (numero_processo);

create table feriado (
    id                bigint generated by default as identity primary key,
    descricao         varchar(120) not null,
    data              date         not null,
    repete_todo_ano   boolean      not null,
    abrangencia_nivel varchar(20)  not null check (abrangencia_nivel in ('NACIONAL', 'ESTADUAL', 'COMARCAL')),
    abrangencia_valor varchar(120)
);
create index idx_feriado_data on feriado (data);

create table modelo_documento (
    id                bigint generated by default as identity primary key,
    codigo            varchar(40)  not null,
    nome              varchar(160) not null,
    tipo              varchar(30)  not null
        check (tipo in ('PETICAO_INICIAL', 'CONTESTACAO', 'PROCURACAO', 'PECA_AVULSA')),
    titulo            varchar(160),
    corpo             text         not null,
    pedidos           text         not null,
    endereca_ao_juizo boolean      not null,
    constraint uk_modelo_codigo unique (codigo)
);

create table notificacao (
    id              bigint generated by default as identity primary key,
    destinatario    varchar(160)  not null,
    assunto         varchar(300)  not null,
    corpo           varchar(1000) not null,
    numero_processo varchar(30),
    canal           varchar(20)   not null,
    registrado_em   timestamp(6)  not null
);

create table contrato_honorario (
    id                bigint generated by default as identity primary key,
    numero_processo   varchar(25)   not null,
    modalidade        varchar(20)   not null,
    valor_fixo        numeric(15, 2) not null,
    valor_hora        numeric(15, 2) not null,
    horas_trabalhadas integer       not null,
    percentual_exito  numeric(5, 2)  not null,
    valor_causa       numeric(15, 2) not null,
    valor_contratado  numeric(15, 2) not null,
    celebrado_em      date          not null
);
create index idx_contrato_processo on contrato_honorario (numero_processo);

create table usuario (
    id               bigint generated by default as identity primary key,
    nome             varchar(120) not null,
    email            varchar(160) not null,
    oab              varchar(20)  not null,
    papel            varchar(20)  not null check (papel in ('ADVOGADO', 'CHEFE')),
    senha_codificada varchar(300) not null,
    senha_provisoria boolean      not null default false,
    constraint uk_usuario_email unique (email),
    constraint uk_usuario_oab unique (oab)
);

-- Modulo de apoio (clientes, partes contrarias e audiencias) - entidades anotadas
-- diretamente, colunas sem tamanho declarado herdam varchar(255) do Hibernate.

create table clientes (
    id               bigint generated by default as identity primary key,
    nome             varchar(255) not null,
    cpf_ou_cnpj      varchar(255) not null unique,
    tipo_pessoa      varchar(20)  not null check (tipo_pessoa in ('FISICA', 'JURIDICA')),
    email            varchar(255),
    telefone         varchar(255),
    celular          varchar(255),
    endereco         varchar(255),
    cidade           varchar(255),
    estado           varchar(255),
    cep              varchar(255),
    profissao        varchar(255),
    empresa_trabalho varchar(255),
    observacoes      varchar(500),
    ativo            boolean      not null,
    criado_em        timestamp(6) not null,
    atualizado_em    timestamp(6)
);

create table partes_contrarias (
    id            bigint generated by default as identity primary key,
    nome          varchar(255) not null,
    cpf_ou_cnpj   varchar(255) not null,
    tipo_pessoa   varchar(20)  not null check (tipo_pessoa in ('FISICA', 'JURIDICA')),
    email         varchar(255),
    telefone      varchar(255),
    endereco      varchar(255),
    cidade        varchar(255),
    estado        varchar(255),
    cep           varchar(255),
    observacoes   varchar(255),
    ativa         boolean      not null,
    criada_em     timestamp(6) not null,
    atualizada_em timestamp(6)
);

create table audiencias (
    id                bigint generated by default as identity primary key,
    numero_processo   varchar(255) not null unique,
    nome_parte_autora varchar(255) not null,
    data_hora_inicio  timestamp(6) not null,
    data_hora_fim     timestamp(6) not null,
    sala              varchar(255) not null,
    observacoes       varchar(500),
    ativa             boolean      not null,
    criada_em         timestamp(6) not null,
    atualizada_em     timestamp(6)
);
