-- praxis: escritorio (Acesso). Login unico por escritorio; ele cadastra os
-- proprios advogados dentro do sistema (tabela advogado, ja existente).

create table escritorio (
    id               bigint generated by default as identity primary key,
    nome             varchar(160) not null,
    cnpj             varchar(20),
    email            varchar(160) not null,
    telefone         varchar(20),
    uf               varchar(2),
    comarca          varchar(120),
    senha_codificada varchar(300) not null,
    constraint uk_escritorio_email unique (email)
);
