create table comarca (
    id bigint generated by default as identity primary key,
    nome varchar(160) not null,
    municipio varchar(120) not null,
    uf varchar(2) not null,
    tribunal varchar(120) not null,
    endereco varchar(300),
    telefone varchar(30),
    email varchar(160),
    horario_atendimento varchar(120),
    observacoes varchar(1000),
    data_cadastro date not null
);

create table vara_judicial (
    id bigint generated by default as identity primary key,
    comarca_id bigint not null references comarca (id),
    nome varchar(160) not null,
    competencia varchar(120) not null,
    endereco varchar(300),
    telefone varchar(30),
    email varchar(160),
    horario_atendimento varchar(120),
    observacoes varchar(1000),
    data_cadastro date not null
);

create index idx_vara_judicial_comarca on vara_judicial (comarca_id);
create unique index uk_comarca_local_nome on comarca (uf, municipio, nome);
create unique index uk_vara_judicial_comarca_nome on vara_judicial (comarca_id, nome);
