create table kanban_coluna (
    id bigint generated by default as identity primary key,
    versao bigint not null,
    nome varchar(60) not null,
    cor varchar(7) not null,
    ordem integer not null,
    conclusiva boolean not null
);

create table kanban_tarefa (
    id bigint generated by default as identity primary key,
    versao bigint not null,
    numero_processo varchar(30) not null references processo (numero_cnj),
    coluna_id bigint not null references kanban_coluna (id),
    titulo varchar(160) not null,
    descricao varchar(3000),
    prioridade varchar(20) not null,
    responsavel_id bigint references advogado (id),
    vencimento date,
    ordem integer not null,
    criada_em date not null,
    atualizada_em date not null
);

create table kanban_checklist (
    tarefa_id bigint not null references kanban_tarefa (id),
    ordem integer not null,
    texto varchar(200) not null,
    concluido boolean not null,
    primary key (tarefa_id, ordem)
);
create index idx_kanban_tarefa_coluna_ordem on kanban_tarefa (coluna_id, ordem);
create index idx_kanban_tarefa_processo on kanban_tarefa (numero_processo);
